# Generated by Django 2.2 on 2019-04-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bna_app', '0002_auto_20190418_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
