# Generated by Django 2.2 on 2019-04-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bna_app', '0003_author_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='bna_app.Book'),
        ),
    ]
